#!/bin/sh

### BEGIN INIT INFO
# Provides:          vpower
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ANT+ Virtual Power service
# Description:       Virtual Power service - see https://github.com/dhague/vpower
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/boot/vpower
DAEMON=$DIR/vpower.py
DAEMON_NAME=vpower

# Add any command line options for your daemon here
DAEMON_OPTS="/boot/vpower.cfg"

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi I2C from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    (ifconfig | grep HWaddr) && log_daemon_msg "Attempt to install requirements for $DAEMON_NAME daemon" \
        && pip install -r $DIR/requirements.txt
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --no-close --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER \
        --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
